use_frameworks!

platform :ios, '9.0'

target 'ReusableComponents_Example' do
  pod 'ReusableComponents', :path => '../'

  target 'ReusableComponents_Tests' do
    inherit! :search_paths

    
  end
end
